# Generated by Django 3.0.3 on 2022-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufname', models.CharField(max_length=10)),
                ('stulname', models.CharField(max_length=10)),
                ('stugrade', models.CharField(max_length=8)),
            ],
        ),
    ]
